### ISSUE TITLE
Volume decreasing with every Jellyfin restart on LG TV

### ISSUE THREAD

**Issue by Karkunow** [jellyfin/jellyfin-webos#233] opened 2024-06-10 16:20 UTC
Volume decreasing with every Jellyfin restart on LG TV.
After some amount of restarts it goes to 0 and there is no sound on any movies.

**Comment by andaril** [comment] 2024-06-10 16:57
Experiencing same issue on lg c3.
Now i'm having no sound in any video with fine logs.

**Comment by Karkunow** [comment] 2024-06-10 17:15
@andaril you can re-install Jellyfin and it helps to solve it for some time

**Comment by holcus** [comment] 2024-06-14 20:59
Same issue, reinstall helps. Lg c3

**Comment by Sebby75** [comment] 2024-06-15 14:53
Same issue on LG 43UJ750V (webos 2.0), Jellyfin 1.2.2 from LG appstore, 
Once it goes silent, the only solution seem to be reinstalling app.

**Comment by dmitrylyzo** [comment] 2024-06-15 15:02
I can't reproduce this in the emulator - tried: start app, start video playback, exit app and repeat.

I wonder if volume just changes by wheel, because there's no check if it happens on TV.

**Comment by Sebby75** [comment] 2024-06-15 18:10
> I wonder if volume just changes by wheel, because there's no check if it happens on TV.

You are correct !! Just checked this.. wheel does indeed change volume (there is no indication at all on tv screen).. 
this works completely independent from normal tv volume control..

**Comment by Karkunow** [comment] 2024-06-15 18:13
@dmitrylyzo @Sebby75 what is the "wheel"? how can I regulate it?

**Comment by Sebby75** [comment] 2024-06-15 18:16
![image](https://github.com/jellyfin/jellyfin-webos/assets/72308577/0c371dce-4f33-4983-9f4f-f6b36ee3f742)

It's in the centre of LG Magic Remote

**Comment by holcus** [comment] 2024-06-15 18:43
Makes sense I was using down wheel to get the cursor up

**Comment by Sebby75** [comment] 2024-06-15 20:16
> Makes sense I was using down wheel to get the cursor up. It's not a bug, it's a feature

Well.. no other app has this (Netflix, Prime Video)... I don't really understand why second independent volume control is needed. Especially when there is no indication on the screen that you are actually changing anything,

**Comment by dmitrylyzo** [comment] 2024-06-15 20:28
It is definitely a bug - TV has a physical volume control. Until some time, TV remotes didn't have a wheel on them, so it didn't bother anyone.

**Comment by Karkunow** [comment] 2024-06-15 21:32
Omg, it wasn't obvious at all! :) 
But yes - wheel up - and it is working now.
On LG TV I can't see any kind of volume change in UI while using the wheel - but it changes.

**Comment by thethingexe** [comment] 2024-06-17 17:40
I uninstalled Jellyfin-WebOS 1.2.2 and installed 1.1.0 and the wheel changing the volume is also in that version.

Has this feature always existed? Or was this a new feature in Jellyfin Server 10.9.X?

**Comment by dmitrylyzo** [comment] 2024-06-19 13:36
> Or was this a new feature in Jellyfin Server 10.9.X?

Yes, it was added in 10.9 (https://github.com/jellyfin/jellyfin-web/pull/4435).

> I uninstalled Jellyfin-WebOS 1.2.2 and installed 1.1.0 and the wheel changing the volume is also in that version.

The app is just a wrapper, so it takes the UI from the server. The app may have some minor changes to adjust something platform specific.

**Comment by Qrrbrbirlbel** [comment] 2024-07-21 19:58
I know this will be fixed in 10.9.9 …

> Just checked this.. wheel does indeed change volume (there is no indication at all on tv screen).

I had the same problem. Had to turn up my TV sound extremely to the point that I could hear some white noise. Uninstalled Homebrew Jellyfin and installed proper and it was fixed so I didn't give it much thought.

However, visiting the server via the built-in browser dialing the wheel does bring up a graphical element that shows this. Which finally made me test the wheel in the proper app and figuring this out for myself.

It is an interesting feature if you know about it but it's also quite pointless since the TV has its own volume control.

**Comment by holcus** [comment] 2024-07-21 20:02
It has use if you passthrough sound to avr/soundbar

**Comment by Randalix** [comment] 2024-08-10 14:04
I had the same problem. Needed to increase my Tv volume to insane amounts.
Imo controlling volume with the wheel shoudl be either removed or there needs to be a visual indicator that shows the change happening. Wihtout this thread I would have never assumed that the volume can be changed with the magic remotes center wheel.

**Comment by dmitrylyzo** [comment] 2024-08-10 15:36
Fixed by https://github.com/jellyfin/jellyfin-web/pull/5740

**Closed by dmitrylyzo** 2024-08-10 15:36 UTC
Labels: bug
