### ISSUE TITLE
Error -27 while trying to connect to host

### ISSUE THREAD

**Issue by bioblatt** [jellyfin/jellyfin-webos#200] opened 2024-02-13 08:09 UTC
I'm always getting error -27 on version 1.1.2 when I try to connect to the host server on my LG TV (65C3) on the most current WebOS version. Jellyfin does work on other devices in the same network...

I tried using http and the X-Frame-Options mentioned in an older post. Without success.

The Jellyfin server runs on version 10.8.13

Can somebody please help me? Thank you very much

**Comment by bioblatt** [comment] 2024-02-13 08:55
> Can you access the server via the built-in browser on webOS?

yes, thats works

**Comment by dmitrylyzo** [comment] 2024-02-13 09:08
Are you using a reverse proxy? If yes, try connecting by IP.

**Comment by bioblatt** [comment] 2024-02-13 13:14
Yes I use a proxy so that everything goes over port 443 and 80. 

Using the IP address did also not work.

**Comment by dmitrylyzo** [comment] 2024-02-13 13:22
I meant try connecting bypassing the proxy: `http://IP:8096` (8096 is Jellyfin's default port).

**Comment by bioblatt** [comment] 2024-02-13 13:29
Yes I did that, the server is still not reachable. I'm also not able to login on different devices by using the public IP.

Just FYI, the LG TV I was talking about is not in the same local network of the server.

**Comment by dmitrylyzo** [comment] 2024-02-13 15:16
> Yes I did that, the server is still not reachable. I'm also not able to login on different devices by using the public IP.
> 
> Just FYI, the LG TV I was talking about is not in the same local network of the server.

Oh. I thought it is in the same network reading `Jellyfin does work on other devices in the same network...`. So it cannot be bypassed without opening ports.

One of the known things that causes this error is `X-Frame-Options` (_you seem to know_). WebOS app uses iframe to open remote webui, other apps do not. Mentioned header blocks requests from the app. It must be removed from the reverse proxy config.

If `X-Frame-Options` is already removed, you need to find out if the request from the app reaches the proxy (_see logs of the proxy_) and what the response of the proxy is.

**Comment by Dycelll** [comment] 2024-02-13 17:27
The problem is that you should first determine where the problem resides. 
Put your TV and jellyfin on the same network, validate that the problem is resolved by following dmitrylyzo’s advice. If you determine that the problem is in the reverse proxy (which is extremely likely), please post the reverse proxy software you are using and logs. 

Be careful not to to post any credentials or internal information.

**Comment by bioblatt** [comment] 2024-02-13 22:00
Sorry my mistake. I just checked my X-Frame-Options again in the nginx config. Seems like forgot to add a line.
I'm now able to login :) Thanks for the help!

**Closed** 2024-02-14 10:59 UTC
