### ISSUE TITLE
Playback menu failing on WebOS 5.10.4

### ISSUE THREAD

**Issue by joseantmazonsb** [jellyfin/jellyfin-webos#15] opened 2020-02-13 18:57 UTC
Hello there, first of all I want to thank the entire Jellyfin community for doing such a great effort to keep this project alive under open source licenses. You are the real MVP.

That said, I've just compiled the ipk and tested it with my jellyfin service only to find out that whenever I play a video (movie or tv show), the remote control will only display the playback menu if I hit left or right arrows, consequently rewinding or forwarding the content. Furthermore, whenever I move through the menu (say I want to hit pause or display the audio options for a given movie), as I'm using left and right arrows, the video keeps rewinding or forwarding its content. 

Also, I have also noticed other minor bugs:

1. Sometimes the spinning wheel that indicates that something is being loaded is still on screen after the task is done (although this has not happened while playing a video, but navigating through the app). 
2. The back button of the remote doesn't work as the back arrow does (don't now if this is intented but I can assure you that it's annoying).

Finally, I took a look at the source code and well, I have to say it is poorly documented. I have no experience programming webOS apps, but I'm doing a little research and I think I could do some workaround and do a pull request if everything works properly.

**Comment by JustAMan** [comment] 2020-02-14 11:12
Which Jellyfin server version are you using? WebOS app is basically a gateway to show you a normal JF web UI (with a few small quirks). Also cc @dmitrylyzo

**Comment by TheYuju12** [comment] 2020-02-14 11:27
> Which Jellyfin server version are you using? WebOS app is basically a gateway to show you a normal JF web UI (with a few small quirks). Also cc @dmitrylyzo

Hi, I'm using Jellyfin 10.4.3.0 over Raspbian 10 buster (raspberry pi 4 with kernel 4.19.102-v7l+). Also, I noticed what you say about the web UI when looking at the code last night and trying to do something through the webOS app only to find out I couldn't do nothing from there

**Comment by dmitrylyzo** [comment] 2020-02-14 11:30
After my PR, webOS app master branch only works with nightly. I thought about backward compatibility: it is simpler to add Back handling to v10.4.3. Then it will be usable, but it has no (focus, scroll)-related features introduced in master. I hope v10.5.0 will be released soon :wink:

**Comment by JustAMan** [comment] 2020-02-14 11:32
I don't think we should make a lot of backward compatibility yet - usually this makes code harder to maintain and improve, and we didn't have a release of WebOS app yet.

So @TheYuju12 I think you'd have to stick to nightly builds of Jellyfin server until 10.5.0 hits, or WebOS app behaviour would be suboptimal.

**Comment by TheYuju12** [comment] 2020-02-14 11:41
Okay then, I'll try the most recent nightly version. Thank you guys :)

**Comment by TheYuju12** [comment] 2020-02-17 11:54
Well, I've been a little busy this weekend but I just installed the nightly 10.5 and tried the WebOS app. Indeed, the experience has improved: the back button is now useful and there are no unwanted rewind or forward while navigating through the menu. However, the subtitles options icon is an X, and for the next/previous episode

**Comment by JustAMan** [comment] 2020-02-17 15:13
Missing icons could be fixed by https://github.com/jellyfin/jellyfin-web/pull/814

**Comment by Narfinger** [comment] 2020-02-18 06:33
Is this a duplicate of https://github.com/jellyfin/jellyfin-web/issues/622? The last comment seems like https://github.com/jellyfin/jellyfin-web/issues/622 can  be closed now.

**Comment by dmitrylyzo** [comment] 2020-02-18 08:21
> Is this a duplicate of [jellyfin/jellyfin-web#622](https://github.com/jellyfin/jellyfin-web/issues/622)?

No. I just turned off native handling of button `Back`, so latest webOS app doesn't work with v10.4.3

**Comment by TheYuju12** [comment] 2020-02-18 14:09
> Missing icons could be fixed by [jellyfin/jellyfin-web#814](https://github.com/jellyfin/jellyfin-web/pull/814)

Will the changes made in the pull request of that issue be included in the 10.5 version?

**Comment by JustAMan** [comment] 2020-02-18 14:29
Most likely.

**Closed** 2020-12-13 23:10 UTC
