### ISSUE TITLE
Reason why app has failed to meet LG's guidlines

### ISSUE THREAD

**Issue by dab2020** [jellyfin/jellyfin-webos#42] opened 2021-04-08 05:26 UTC
Going through LG's webOS documentation, I found that the app can be rejected if not optimized or even if compatibility issues.
According to their guidelines, the icon/logo files need to be in the home directory, (considering jellyfin-webos/org.jellyfin.webos/ is root) the icon/logo should not be labeled submission-icon.png. but two separate files icon.png and large-icon.png. the icon.png should be 80x80 and large-icon 400x400. I am myself a developer and have created apps for webOS so if you need any help, I am available.

**Comment by MrTimscampi** [comment] 2021-04-08 12:43
The metadata check is already passed and we're awaiting more info from LG at this time.

@anthonylavado is the one monitoring the process and I'm sure he'll have more to say when hear back from LG.

Although thanks for the proposal, we always welcome some help :) This repository is mainly a wrapper around the web client, so if something arises during testing, chances are most of the work would have to be done over there.

**Comment by oddstr13** [comment] 2021-04-08 21:25
Thanks for the offer of help! :smiley: 

I'm closing this issue as a duplicate of #28.

**Closed** 2021-04-08 21:25 UTC
